### ISSUE TITLE
The memory size of this project.

### ISSUE THREAD

**Issue by zzzbbs** [wkwan7/Category_Level_Manipulation#1]
Excuse me, 
I am a researcher of imitation learning and want to reproduce the results of your paper.
When I sh run_GAIL_baseline_door.sh, it seems like my memory is not enough to run this project and then killed.
So I want to know the memory(RAM) size of what you used in this task.  
I would be very thankful if you could send me more information about this.

my current device memory : 32G DDR5

**Comment by wkwan7** [comment]
> Excuse me, I am a researcher of imitation learning and want to reproduce the results of your paper. When I sh run_GAIL_baseline_door.sh, it seems like my memory is not enough to run this project and then killed. So I want to know the memory(RAM) size of what you used in this task. I would be very thankful if you could send me more information about this.
> 
> my current device memory : 32G DDR5

Hi zzzbbs,
We ran our experiments on a remote server and it may need 100G+ or larger memory. The data provided by ManiSkill is large because it consists point cloud of the scene and has a lot of  trajectories for each instance.
Besides, we find that when we only use 1/5 of data for each instance, it still works very well. So I recommand you to random select a part of data for each instance (maybe 1/10 or smaller) and reduce the buffer size to see if this works for you. 
Hope these will help you!

**Comment by zzzbbs** [comment]
Thank you very much for your reply!!! I will try to reduce the buffer size.
